package com.donpedromz.network;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.EOFException;
import java.io.IOException;
import java.net.Socket;
import java.net.SocketException;

import com.donpedromz.business.ProcessingPolicy;

/**
 * @author juanp
 * @version 1.0
 * Maneja la comunicación con un cliente TCP, aplicando una política de
 * procesamiento a los mensajes recibidos y enviando respuestas.
 */
public class ClientHandler implements Runnable {
    /**
     * Socket del cliente conectado. Se utiliza para leer mensajes y enviar respuestas.
     */
    private final Socket clientSocket;
    /**
     * Política de procesamiento que se aplica a los mensajes recibidos del cliente.
     */
    private final ProcessingPolicy processingPolicy;

    /**
     * Crea un nuevo manejador de cliente con el socket y la política de procesamiento especificados.
     * @param clientSocket El socket del cliente conectado. No debe ser null.
     * @param processingPolicy La política de procesamiento que se aplicará a los mensajes recibidos. No debe ser null.
     */
    public ClientHandler(Socket clientSocket, ProcessingPolicy processingPolicy) {
        this.clientSocket = clientSocket;
        this.processingPolicy = processingPolicy;
    }

    /**
     * Ejecuta el manejador de cliente, leyendo un mensaje del cliente, aplicando la política de procesamiento
     */
    @Override
    public void run() {
        try (
        DataInputStream input = new DataInputStream(clientSocket.getInputStream());
        DataOutputStream out = new DataOutputStream(clientSocket.getOutputStream())){
            String receivedMessage = input.readUTF();
            System.out.println("[TCP] Received from client: " + receivedMessage);
            String response = processingPolicy.apply(receivedMessage);
            if (response == null) {
                response = "[TCP] Error: no response generated by processing policy";
            }
            out.writeUTF(response);
            out.flush();
        } catch (EOFException | SocketException e) {
            System.out.println("[TCP] Client connection closed");
        } catch (IOException e) {
            System.out.println("[TCP] Error handling client connection");
            throw new RuntimeException(e);
        }
    }
}
